apiVersion: apps/v1
kind: Deployment
metadata:
  name: silly-app
  labels:
    app: silly-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: silly-app
  template:
    metadata:
      labels:
        app: silly-app
    spec:
      containers:
      - name: silly-app
        image: nginx:latest
---
apiVersion: v1
kind: Service
metadata:
  name: silly-app
spec:
  selector:
    app: silly-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
